# Generated by Django 5.0.7 on 2025-06-16 00:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Semester')),
                ('am', models.CharField(max_length=100, verbose_name='University')),
                ('subject_name_lithuanian', models.CharField(max_length=200, verbose_name='Subject Name (Lithuanian)')),
                ('subject_name_english', models.CharField(max_length=200, verbose_name='Subject Name (English)')),
                ('language', models.CharField(choices=[('LT', 'Lithuanian'), ('EN', 'English'), ('DE', 'German'), ('FR', 'French'), ('ES', 'Spanish')], max_length=2, verbose_name='Language')),
                ('selection_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('ELECTIVE', 'Elective'), ('FREE_ELECTIVE', 'Free Elective')], max_length=20, verbose_name='Selection Type')),
                ('assessment_form', models.CharField(choices=[('EXAM', 'Exam'), ('ASSESSMENT', 'Assessment'), ('PROJECT', 'Project'), ('PRESENTATION', 'Presentation')], max_length=20, verbose_name='Assessment Form')),
                ('study_part', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('DOCTORAL', 'Doctoral')], max_length=20, verbose_name='Study Part')),
                ('planned_credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Planned Credits')),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Hours')),
                ('credits_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Credits Received')),
                ('original_grade', models.CharField(blank=True, max_length=10, verbose_name='Original Grade')),
                ('original_credits', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Original Credits')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Grade')),
                ('level_achieved', models.CharField(blank=True, choices=[('A', 'A (Excellent)'), ('B', 'B (Good)'), ('C', 'C (Satisfactory)'), ('D', 'D (Poor)'), ('F', 'F (Fail)')], max_length=1, verbose_name='Level Achieved')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Exam Date')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['-s', 'subject_name_english'],
            },
        ),
    ]
